### ISSUE TITLE
pass flutter web build arguments like --base-href  

### ISSUE THREAD

**Issue by HosamHasanRamadan** [kevmoo/peanut.dart#113] opened 2021-09-09 13:13 UTC
flutter web build optional arguments not provided by `peanut` so running command like 
``` bash
peanut --web-renderer=canvaskit --base-href="/gtihub_repo/"
```
is not possible.

**Comment by kevmoo** [comment] 2021-09-09 19:11
Duplicate of #107

**Closed by kevmoo** 2021-09-09 19:11 UTC

**Comment by kevmoo** [comment] 2021-09-13 23:19
Fixed in peanut v4.1.0
